### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by msolovyov** [SamVerschueren/aws-sns-publish#2]
Tried using this library to send an SMS directly to a phone number in a lambda function. It always times out. 

Same issue with publishing to a topic arn.

**Comment by SamVerschueren** [comment]
What went wrong? Was it the library? Was it something else?

**Comment by msolovyov** [comment]
Turned out that since my lambda was in vpc I need to add a nat gateway(that's in a subnet that routes to an internet gateway) to the lamba subnets. So the library isn't at fault.
