### ISSUE TITLE
Missing AWS SDK

### ISSUE THREAD

**Issue by ojizero** [SamVerschueren/aws-sns-publish#3]
The AWS SDK is set as [devdependency](https://github.com/SamVerschueren/aws-sns-publish/blob/master/package.json#L36) only, it should either be set as a normal dependency, or as a peer dependency, since the whole library doesn't function without the SDK.

I think setting it as a peer dependency is better though, since you seem it would allow users of AWS Lambda to use the Lambda's bundled version of the SDK.

**Comment by SamVerschueren** [comment]
You are right, it should be a peer dependency. Thanks! PR welcome.

**Comment by ojizero** [comment]
@SamVerschueren just opened one #4
