### ISSUE TITLE
Incompatible version with XO

### ISSUE THREAD

**Issue by ojizero** [SamVerschueren/aws-sns-publish#5]
This package supports Nodejs >= 4, while XO supports version >=6, this causes builds to fail on Node 4 in Travis due to failing to run XO. Should either drop support to Node 4 (which reached its EOL), or with less of a breaking change, either modify .travis.yml to not run XO against Node 4 or lock to XO version prior to `0.21.0` which dropped Node 4 support. Not sure which approach is best though.

**Comment by SamVerschueren** [comment]
Thanks for the fix!
